---

    - name: Install required system packages
      apt: 
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
      become: yes
      tags:
        - always

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: yes

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
      become: yes

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
      become: yes

    - name: Get OS details
      shell: uname -s
      register: os
    - name: Get Arch details
      shell: uname -m
      register: arch 

    - name: Install Docker Compose (if configured).
      get_url:
        url: https://github.com/docker/compose/releases/download/1.25.1/docker-compose-{{ os.stdout }}-{{ arch.stdout }}
    #   dest: "{{ docker_compose_path }}"
        dest: /usr/local/bin/docker-compose
        mode: 0755
      become: yes
      
    - name: Install Docker Module for Python
      pip:
        name: docker
